# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirmation_capture.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(321, 110)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 251, 21))
        self.label.setObjectName("label")
        self.non = QtWidgets.QPushButton(self.centralwidget)
        self.non.setGeometry(QtCore.QRect(170, 40, 141, 41))
        self.non.setObjectName("non")
        self.non.clicked.connect(non)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 40, 141, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(oui)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 321, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">L\'image vous convient-elle ?</span></p></body></html>"))
        self.non.setText(_translate("MainWindow", "Non, recommencer"))
        self.pushButton_3.setText(_translate("MainWindow", "Oui, enregistrer"))


def oui():
    with open('choix.txt', 'w') as f:
        f.write('oui')
    MainWindow.close()


def non():
    with open('choix.txt', 'w') as f:
        f.write('non')
    MainWindow.close()


def main_confirm_capture():
    QtCore.qInstallMessageHandler(handler)
    global MainWindow
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    app.exec_()

def handler(msg_type, msg_log_context, msg_string):
    pass